package com.example.stocksearchservice.config.runtime

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(StockSearchRuntimeSafetyProperties::class)
class StockSearchRuntimeSafetyConfiguration
