package com.example.stockpurchaseservice.config.runtime

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(StockPurchaseRuntimeSafetyProperties::class)
class StockPurchaseRuntimeSafetyConfiguration
