package com.example.stockpurchaseservice.config.broker

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(KisBrokerGatewayProperties::class)
class KisBrokerGatewayConfiguration
