spring.application.name=stock-search-service
server.port=8082
spring.profiles.include=kafka
akra.temporal.enabled=true
akra.temporal.target=127.0.0.1:7233
akra.temporal.namespace=default
akra.temporal.task-queue=stock-search-scheduler
akra.temporal.schedules.top-volume.enabled=true
akra.temporal.schedules.top-volume.schedule-id=stock-search-top-volume-stocks
akra.temporal.schedules.top-volume.interval=1m
