package com.example.strategyexecutionservice.config.runtime

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(StrategyExecutionRuntimeSafetyProperties::class)
class StrategyExecutionRuntimeSafetyConfiguration
