package com.example.stockpurchaseservice.config.observability

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(OperationalAlertProperties::class)
class OperationalAlertConfiguration
